Remove boot image profile configuration
Deleted settings related to boot image profile usage and its location from art.mk. This simplifies the build configuration and may reflect a change in how boot image profiles are managed.[100% 2/2] analyzing Android.bp files and generating ninja file at out/soong/bu
FAILED: out/soong/build.lineage_sargo.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basenam
e "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --to
p "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/
soong/soong.lineage_sargo.variables -o out/soong/build.lineage_sargo.ninja -l o
ut/.module_paths/Android.bp.list --available_env out/soong/soong.environment.av
ailable --used_env out/soong/soong.environment.used.lineage_sargo.build Android
.bp
error: prebuilts/module_sdk/art/current/sdk/Android.bp:36:1: module "prebuilt_a
rt-bootclasspath-fragment" variant "android_common": source path "frameworks/ba
se/config/boot-image-profile.txt" does not exist
error: prebuilts/runtime/mainline/i18n/sdk/Android.bp:9:1: module "prebuilt_i18
n-bootclasspath-fragment" variant "android_common": source path "frameworks/bas
e/config/boot-image-profile.txt" does not exist
error: art/build/boot/Android.bp:41:1: module "art-bootclasspath-fragment" vari
ant "android_common": source path "frameworks/base/config/boot-image-profile.tx
t" does not exist
11:55:37 soong bootstrap failed with: exit status 1

#### failed to build some targets (40 seconds) ####